version: '3.4'

services:
  golangmysqlcrudbookstoremanagementapimaster:
    image: golangmysqlcrudbookstoremanagementapimaster
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
